config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :teams do
  	  resources :games
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "pages/home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
	validates :game_point, presence: true

  belongs_to :team
end

app/models/team.rb
class Team < ApplicationRecord
	has_many :games
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]
  # GET /games
  # GET /games.json
  def index
    @team = Team.find(params[:team_id])
    @game = @team.games
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @team = Team.find(params[:team_id])
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
     @team = Team.find(params[:team_id])
  end

  # POST /games
  # POST /games.json
  def create

    @team = Team.find(params[:team_id])
    @game = @team.games.new(game_params)


    respond_to do |format|
      if @game.save
        set_max_team_point
        format.html { redirect_to @team, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render 'teams/show'}
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
         set_max_team_point
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy   
    respond_to do |format|
      format.html { redirect_to team_path(@game.team_id), notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:game_point, :team_id)
    end

    def set_max_team_point
      #I must add this for destroy opation, 
      if @team_point != @team.games.maximum('game_point')
           @team.point = @team.games.maximum('game_point')
           @team.save
      end
          
    end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
	end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render 'team/show' }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: 'Team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.require(:team).permit(:name, :point)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/games/_form.html.erb
<%= form_with(model: [@team, @team.games.build],local: true) do |form| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :game_point %>
    <%= form.text_field :game_point %>
  </div>

  <div class="field">
    <%# form.label :team_id %>
    <%# form.text_field :team_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/games/_index.html.erb
<p id="notice"><%= notice %></p>

<h1>Games</h1>

<table>
  <thead>
    <tr>
      <th>#</th>
      <th>Game point</th>
      <th>Team</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @team.games.order(:game_point).each do |game, index| %>
      <tr>
        <td><%= index.to_i %></td>
        <td><%= game.game_point %></td>
        <td><%= game.team.name%></td>
        <td><%= link_to 'Show', team_game_path(game.team_id, game.id) %></td>
        <td><%= link_to 'Edit', edit_team_game_path(game.team_id, game.id) %></td>
        <td><%= link_to 'Destroy', team_game_path(game.team_id, game.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% console %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', team_game_path(@game.team_id, @game.id) %> |
<%= link_to 'Back', team_path(@game.team_id) %>

app/views/games/new.html.erb
<h1>New Game</h1>
<%= render "games/form" %>

<%# link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Game point:</strong>
  <%= @game.game_point %>
</p>

<p>
  <strong>Team:</strong>
  <%= @game.team.name %>
</p>

<%= link_to 'Edit', edit_team_game_path(@game.team_id, @game.id) %> |
<%= link_to 'Back', team_path(@game.team_id) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScoringSysteam</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
<br>

<div class="container">

<div class="card">
	<div class="card-header">
		<div class="row justify-content-between">
			    <div class="col">
					<h5>Team Number - Team Name </h5>
					<footer class="blockquote-footer"> team school name</footer>
				</div>
				<div class="col">
					<h5 class="text-right col-xs-2">Rank #15/30</h5>
				</div>

		</div>	
	</div>
  <div class="card-body">


  	<div class="row">
  <div class="col-sm"><h4>game play: 5</h4></div>
  <div class="col-sm"><h4>best point: 155/400</h4></div>
  <div class="col-sm"><h4>best time: 15:15s</h4></div>
</div>

	<br>
  		<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">First</th>
      <th scope="col">Last</th>
      <th scope="col">Handle</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>Mark</td>
      <td>Otto</td>
      <td>@mdo</td>
    </tr>
    <tr>
      <th scope="row">2</th>
      <td>Jacob</td>
      <td>Thornton</td>
      <td>@fat</td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td>Larry</td>
      <td>the Bird</td>
      <td>@twitter</td>
    </tr>
  </tbody>
</table>

    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>
</div>